[[languages]]
name = "JSON"

[[languages.formatters]]
command = "jq"
args = ["."]

[[languages]]
name = "Shell"

[[languages.formatters]]
command = "shfmt"
args = ["-s", "-i", "2", "-"]


[[languages]]
name = "Markdown"

[[languages.formatters]]
command = "mdformat"
args = ["-"]

[[languages]]
name = "Nix"

[[languages.formatters]]
command = "nixfmt"

[[languages.formatters]]
command = "alejandra"

[[languages]]
name = "YAML"

[[languages.formatters]]
command = "prettier"
args = ['--parser', 'yaml']



[[languages]]
name = "TOML"

[[languages.formatters]]
command = "tomll"

[[languages]]
name = 'TSV'
formatters = [{}]

[[languages]]
name = 'Python'

[[languages.formatters]]
command = "uvx"
args = ['ruff', 'format', "-"]

[[languages]]
name = "Lua"

[[languages.formatters]]
command = "stylua"
args = [ "-"]

[[languages]]
name = "Git Attributes"
formatters = [{}]

[[languages]]
name = "Ignore List"
formatters = [{}]

[[languages]]
name = "Public Key"
formatters = [{}]
